---
title: "AutoTax figure S4: Taxonomy novelty"
author: "Morten Simonsen Dueholm"
date: "2020-05-16"
---

## R-packages
```{r, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
#library(plyr)
library(tidyverse)
#library(broom)
#library(scales)
library(data.table)
```
## Set working directory
```{r, echo=FALSE, message=FALSE, warning=FALSE}
setwd("C:/Users/Morten Dueholm/Dropbox/Projects/Ongoing projects/P001_AutoTax/R/Novelty/190906")
```

## Import data
```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Read mapping results
df <- read.delim("data/tax_complete.csv",
                      sep = ",",
                      header = TRUE,
                      quote = "\"",
                      fill = TRUE,
                      check.names = FALSE,
                      stringsAsFactors = FALSE)

```

# Novelty Calculations
```{r, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
Novelty <- df %>%
  group_by(Phylum) %>%
  summarize("New species"= uniqueN(Species[grepl("denovo", Species)]),
            "New genera"= uniqueN(Genus[grepl("denovo", Genus)]),
            "New families"= uniqueN(Family[grepl("denovo", Family)]),
            "New orders"= uniqueN(Order[grepl("denovo", Order)]),
            "New classes"= uniqueN(Class[grepl("denovo", Class)]))%>%
  gather(2:6, key = "Taxonomic_rank", value = "Counts")%>%
    mutate(Taxonomic_rank=factor(Taxonomic_rank, levels=c("New classes","New orders","New families","New genera","New species"))) %>%
  filter(Counts>0)
```

## Plot histogram
```{r, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
p1 <- ggplot(data=Novelty, aes(x=Phylum, y=Counts, fill=Taxonomic_rank)) +
  theme_bw() +
  geom_bar(color="black",stat="identity",position = "identity", width=0.8) +
  theme(axis.text.x = element_text(angle = 90, vjust=0.5, hjust = 1)) +
  scale_fill_brewer(palette="RdYlBu")+
  ylab("Number of taxa that are assigned denovo names") + 
  theme(axis.title.x=element_blank())+
  theme(legend.position = "none")+
  facet_grid(Taxonomic_rank~., scales="free")
```

## Export data
```{r, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
ggsave(filename="output/FigureS4.pdf", plot=p1, width=8, height=7, useDingbats=FALSE, limitsize=FALSE)
```