---
title: "FigureS3"
author: "CKO and MKDD"
date: '2023-09-17'
output: html_document
---
#Load packages
```{r}
library(data.table)
library(ggplot2)
library(tidyverse)
library(patchwork)
```

Load data 
```{r}
passes_pacbio <- read.delim("data/numb_passes.sam", header = F, sep = "")
passes_pacbio <- setnames(passes_pacbio, "V1", "Seq")
passes_pacbio <- setnames(passes_pacbio, "V2", "Number_passes")

coverage_clonal <- read.delim("data/coverage_clonal.txt", header = F, sep = "")
coverage_clonal <- setnames(coverage_clonal, "V1", "Seq")
coverage_clonal <- setnames(coverage_clonal, "V2", "UMI_coverage")

coverage_umi <- read.delim("data/coverage_umi.txt", header = F, sep = "")
coverage_umi <- setnames(coverage_umi, "V1", "Seq")
coverage_umi <- setnames(coverage_umi, "V2", "UMI_coverage")

PacBio_map <- data.table::fread("data/PacBio_mapping_perfect_hits.b6",
                      sep = "\t",
                      header = FALSE,
                      quote = "\"",
                      fill = TRUE,
                      check.names = FALSE,
                      stringsAsFactors = FALSE,
                      select = c(1,5,6))
  PacBio_map <- setnames(PacBio_map, "V1", "Seq")
  PacBio_map <- setnames(PacBio_map, "V5", "Mismatches")
  PacBio_map <- setnames(PacBio_map, "V6", "Gaps")
  PacBio_map <- PacBio_map %>% mutate("Differences" = Mismatches+Gaps) %>% select(c(-Mismatches, -Gaps))
  PacBio_map <- merge(PacBio_map, passes_pacbio, by = "Seq", all.x = T)

UMI_clonal_map <- data.table::fread("data/UMI-clonal_perfect_hits.b6",
                      sep = "\t",
                      header = FALSE,
                      quote = "\"",
                      fill = TRUE,
                      check.names = FALSE,
                      stringsAsFactors = FALSE,
                      select = c(1,6,7))
  UMI_clonal_map <- setnames(UMI_clonal_map, "V1", "Seq")
  UMI_clonal_map <- setnames(UMI_clonal_map, "V6", "Mismatches")
  UMI_clonal_map <- setnames(UMI_clonal_map, "V7", "Gaps")
  UMI_clonal_map <- UMI_clonal_map %>% mutate("Differences" = Mismatches+Gaps) %>% select(c(-Mismatches, -Gaps))
  UMI_clonal_map <- merge(UMI_clonal_map, coverage_clonal, by = "Seq", all.x = T)
  
  
UMI_map <- data.table::fread("data/UMI_mapping_perfect_hits.b6",
                      sep = "\t",
                      header = FALSE,
                      quote = "\"",
                      fill = TRUE,
                      check.names = FALSE,
                      stringsAsFactors = FALSE,
                      select = c(1,6,7))
  UMI_map <- setnames(UMI_map, "V1", "Seq")
  UMI_map <- setnames(UMI_map, "V6", "Mismatches")
  UMI_map <- setnames(UMI_map, "V7", "Gaps")
  UMI_map <- UMI_map %>% mutate("Differences" = Mismatches+Gaps) %>% select(c(-Mismatches, -Gaps))
  UMI_map <- merge(UMI_map, coverage_umi, by = "Seq", all.x = T)
```

# Plot number of mismatches vs coverage for PacBio data
```{r}
vec <- unique(PacBio_map$Number_passes)

list_df <- lapply(vec, function(i) {
  PacBio_map %>% filter(Number_passes == i) %>% 
        count(Differences == 0) %>%
        mutate(Percentage= round(n /sum(n)*100, digits = 2)) %>%
        mutate(Coverage = i) %>%
        select( , !c("n","Differences == 0")) %>%
        slice(2) })

df <- rbindlist(list_df)

zero <- setdiff(vec, df$Coverage)

df_zero <- data.frame(zero) %>% 
  mutate(Percentage = 0) %>%
  rename(Coverage = zero) %>%
  select(Percentage, Coverage)

All_df <- rbind(df, df_zero)

p1 <- ggplot(All_df, 
             aes(Coverage, Percentage)) + 
      geom_col(fill = "#80B1D3")  +
      theme_bw() +
      theme(axis.text.x = element_text(angle = 90, 
                                       hjust = 0.5, 
                                       vjust = 0.5)) +
     theme(text=element_text(size=6, colour = "black"),
           axis.text = element_text(size = 6, colour = "black"),
           legend.text = element_text(size = 6, colour = "black"),
           legend.title = element_text(size = 6, face ="bold", colour = "black")) +
     scale_x_continuous(limits = c(0, 50), 
                         breaks = c(0,10, 20, 30, 40, 50)) +
      ylim(0, 100) +
      ylab("PacBio CCS reads (%)")
```

# Plot number of mismatches vs coverage for Clonal data
```{r}
vec <- unique(UMI_clonal_map$UMI_coverage)

list_df <- lapply(vec, function(i) {
  UMI_clonal_map %>% filter(UMI_coverage == i) %>% 
        count(Differences == 0) %>%
        mutate(Percentage = round(n /sum(n)*100, digits = 2)) %>%
        mutate(Coverage = i) %>%
        select( , !c("n","Differences == 0")) %>%
        slice(2) })

df <- rbindlist(list_df)

zero <- setdiff(vec, df$Coverage)

df_zero <- data.frame(zero) %>% 
  mutate(Percentage = 0) %>%
  rename(Coverage = zero) %>%
  select(Percentage, Coverage)

All_df <- rbind(df, df_zero)

p2 <- ggplot(All_df, 
             aes(Coverage, Percentage)) + 
      geom_col(fill = "#80B1D3")  +
      theme_bw() +
      theme(axis.text.x = element_text(angle = 90, 
                                       hjust = 0.5, 
                                       vjust = 0.5)) +
     theme(text=element_text(size=6, colour = "black"),
           axis.text = element_text(size = 6, colour = "black"),
           legend.text = element_text(size = 6, colour = "black"),
           legend.title = element_text(size = 6, face ="bold", colour = "black")) +
      ylim(0, 100) +
      scale_x_continuous(limits = c(0, 180), 
                         breaks = c(0,20, 40, 60, 80, 100, 120, 140, 160, 180)) +
      ylim(0, 100) +
      ylab("Nanopore UMI_clonal consensus sequences (%)")
```

# Plot mismatches vs coverage 
```{r}
vec <- unique(UMI_map$UMI_coverage)

list_df <- lapply(vec, function(i) {
  UMI_map %>% filter(UMI_coverage == i) %>% 
        count(Differences == 0) %>%
        mutate(Percentage = round(n /sum(n)*100, digits = 2)) %>%
        mutate(Coverage = i) %>%
        select( , !c("n","Differences == 0")) %>%
        slice(2) })

df <- rbindlist(list_df)

zero <- setdiff(vec, df$Coverage)

df_zero <- data.frame(zero) %>% 
  mutate(Percentage = 0) %>%
  rename(Coverage = zero) %>%
  select(Percentage, Coverage)

All_df <- rbind(df, df_zero)

p3 <- ggplot(All_df, 
             aes(Coverage, Percentage)) + 
      geom_col(fill = "#80B1D3")  +
      theme_bw() +
      theme(axis.text.x = element_text(angle = 90, 
                                       hjust = 0.5, 
                                       vjust = 0.5)) +
      theme(text=element_text(size=6, colour = "black"),
           axis.text = element_text(size = 6, colour = "black"),
           legend.text = element_text(size = 6, colour = "black"),
           legend.title = element_text(size = 6, face ="bold", colour = "black")) +
      ylim(0, 100) +
      scale_x_continuous(limits = c(0, 140), 
                         breaks = c(0, 20, 40, 60, 80, 100, 120, 140)) + 
      ylim(0, 100) +
      ylab("Nanopore UMI consensus sequences (%)")
```

# Combine the three plots
```{r}
p <- p1 + p3 + p2
```

Export the plot
```{r}
ggsave(filename="output/FigureS3.pdf", plot=p, width=169, height=40, units = "mm", useDingbats=FALSE, limitsize=FALSE)
```


