---
title: "AutoTax figure 3a: Classification of Amplicons"
author: "Morten Simonsen Dueholm"
date: "2020-04-14"
---

## R-packages
```{r, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
```
## Set working directory
```{r, echo=FALSE, message=FALSE, warning=FALSE}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

## Import data
```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Read mapping results
read_amp_classifications <- function(input) {
  map <- read.delim(input,
                      sep = "\t",
                      header = FALSE,
                      quote = "\"",
                      fill = TRUE,
                      check.names = FALSE,
                      stringsAsFactors = FALSE) %>%
    select(c(1,4)) %>%
    rename(ASV=V1) %>%
    separate(V4, c("Kingdom","Phylum","Class","Order","Family","Genus","Species"),sep=",") %>%
      mutate(Reference = (!!gsub(".*vs_(.+).sintax", "\\1", paste(input)))) %>%
      arrange(readr::parse_number(ASV))
    }

a <- read_amp_classifications("data/V13zotus_vs_FL-ASVs.sintax")
b <- read_amp_classifications("data/V13zotus_vs_FL-ASVs+FL-OTUs-CF%.sintax")
c <- read_amp_classifications("data/V13zotus_vs_FL-ASVs+FL-OTUs-CF+.sintax")
d <- read_amp_classifications("data/V13zotus_vs_gg_16s_13.5.sintax")
e <- read_amp_classifications("data/V13zotus_vs_rdp_16s_v16.sintax")
f <- read_amp_classifications("data/V13zotus_vs_SILVA_138_SSURef_Nr99.sintax")
g <- read_amp_classifications("data/V13zotus_vs_MiDAS_2.1.sintax")
h <- read_amp_classifications("data/V13zotus_vs_Autotax_SILVA_138_SSURef_Nr99.sintax")
i <- read_amp_classifications("data/V13zotus_vs_GTDB_r89.sintax")

Merged_classifications <- bind_rows(a,b,c,d,e,f,g,h,i)

# Read ASV table
  ASVtable <- read.delim("data/V13ASVtab.txt",
                      sep = "\t",
                      header = TRUE,
                      quote = "\"",
                      fill = TRUE,
                      check.names = FALSE,
                      stringsAsFactors = FALSE) %>%
    rename(ASV=1) %>%
      arrange(readr::parse_number(ASV))

# Merge ASV table and mappings
df <- left_join(ASVtable, Merged_classifications, by="ASV")

# Ranked abundance
ranked <- df %>%
  gather(2:49, key="SeqID", value="counts") %>%
  group_by(SeqID,Reference) %>%
  arrange(desc(counts)) %>%
  mutate(rank = row_number(), relative_abundance = counts/sum(counts)*100) %>%
  ungroup() %>%
  gather(2:8, key="Taxonomic_rank", value="Taxonomy") %>%
  mutate(Reference = factor(Reference, levels = c("FL-ASVs","FL-ASVs+FL-OTUs-CF%","FL-ASVs+FL-OTUs-CF+", "gg_16s_13.5", "GTDB_r89", "MiDAS_2.1","rdp_16s_v16", "SILVA_138_SSURef_Nr99","Autotax_SILVA_138_SSURef_Nr99")))

Sample_metadata <- read.delim("data/Sample_metadata.txt",
                      sep = "\t",
                      header = TRUE,
                      quote = "\"",
                      fill = TRUE,
                      check.names = FALSE,
                      stringsAsFactors = FALSE) 

ranked_w_metadata <- left_join(ranked, Sample_metadata, by="SeqID") %>%
  mutate(Environment = factor(Environment, levels = c("WWTP","Anaerobic digester")))
```

Summarize_data
```{r, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
Summary_Genus <- ranked_w_metadata %>%
  filter(relative_abundance > 0.01, Taxonomic_rank==c("Genus")) %>%
  group_by(SeqID, Location, Environment, Reference, Taxonomic_rank) %>%
  summarize("Classified"=100-(sum(is.na(Taxonomy))/n()*100))

Summary_Species <- ranked_w_metadata %>%
  filter(relative_abundance > 0.01, Taxonomic_rank==c("Species")) %>%
  group_by(SeqID, Location, Environment, Reference, Taxonomic_rank) %>%
  summarize("Classified"=100-(sum(is.na(Taxonomy))/n()*100))

Summary <- bind_rows(Summary_Genus,Summary_Species)

Summary_Mean_and_stdev <- Summary %>%
  group_by(Reference, Taxonomic_rank) %>%
  summarize("Mean"=mean(Classified),
            "Stdev"=sd(Classified))

Summary_Genus2 <- ranked_w_metadata %>%
  filter(relative_abundance > 0.001, Taxonomic_rank==c("Genus")) %>%
  group_by(SeqID, Location, Environment, Reference, Taxonomic_rank) %>%
  summarize("Classified"=100-(sum(is.na(Taxonomy))/n()*100))

Summary_Species2 <- ranked_w_metadata %>%
  filter(relative_abundance > 0.001, Taxonomic_rank==c("Species")) %>%
  group_by(SeqID, Location, Environment, Reference, Taxonomic_rank) %>%
  summarize("Classified"=100-(sum(is.na(Taxonomy))/n()*100))

Summary2 <- bind_rows(Summary_Genus2,Summary_Species2)

Summary_Mean_and_stdev2 <- Summary2 %>%
  group_by(Reference, Taxonomic_rank) %>%
  summarize("Mean"=mean(Classified),
            "Stdev"=sd(Classified))
```

## Plot histogram
```{r, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
Figure3a <- ggplot(data=Summary, aes(x=Reference, y=Classified, fill=Reference)) +
  theme_bw() +
  geom_violin(scale = "width") +
  ylab("Percent of ASVs with relative abundance\n higher than 0.01% classified") +
  scale_fill_brewer(palette="RdYlBu")+
  theme(axis.title.x=element_blank()) +
  facet_grid(Taxonomic_rank~Environment) +
  scale_y_continuous(limits = c(0, 100), breaks=seq(0,100,10)) +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 90, vjust=0.5, hjust = 1))

FigureX <- ggplot(data=Summary2, aes(x=Reference, y=Classified, fill=Reference)) +
  theme_bw() +
  geom_violin(scale = "width") +
  ylab("Percent of ASVs with relative abundance\n higher than 0.001% classified") +
  scale_fill_brewer(palette="RdYlBu")+
  theme(axis.title.x=element_blank()) +
  facet_grid(Taxonomic_rank~Environment) +
  scale_y_continuous(limits = c(0, 100), breaks=seq(0,100,10)) +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 90, vjust=0.5, hjust = 1))
```

## Export data
```{r, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
ggsave(filename="output/Figure3a.pdf", plot=Figure3a, width=7, height=7, useDingbats=FALSE, limitsize=FALSE)
ggsave(filename="output/FigureX.pdf", plot=FigureX, width=7, height=7, useDingbats=FALSE, limitsize=FALSE)
```