---
title: "Figure 3: Database evaluation based on V5-V7 amplicon classification"
author: "cko"
date: "2021-09-01"
---

## R-packages
```{r, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
library(data.table)
library(patchwork)
library(tidyverse)
```

## Import data
```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Read mapping results
read_amp_classifications <- function(input) {
  map <- read.delim(input,
                      sep = "\t",
                      header = FALSE,
                      quote = "\"",
                      fill = TRUE,
                      check.names = FALSE,
                      stringsAsFactors = FALSE) %>%
    select(c(1,4)) %>%
    rename(ASV=V1) %>%
    separate(V4, c("Kingdom","Phylum","Class","Order","Family","Genus","Species"),sep=",") %>%
      mutate(Reference = (!!gsub(".*vs_(.+).sintax", "\\1", paste(input)))) %>%
      arrange(readr::parse_number(ASV))
    }

a <- read_amp_classifications("data/zotus_vs_AsCoM.sintax")
b <- read_amp_classifications("data/zotus_vs_GG.sintax")
c <- read_amp_classifications("data/zotus_vs_GTDB.sintax")
d <- read_amp_classifications("data/zotus_vs_RDP.sintax")
e <- read_amp_classifications("data/zotus_vs_SILVA.sintax")

Merged_classifications <- bind_rows(a,b,c,d,e)

# Read ASV table
  ASVtable <- read.delim("data/ASVtable.txt",
                      sep = "\t",
                      header = TRUE,
                      quote = "\"",
                      fill = TRUE,
                      check.names = FALSE,
                      stringsAsFactors = FALSE) %>%
    rename(ASV=1) %>%
      arrange(readr::parse_number(ASV))

# Merge ASV table and mappings
df <- left_join(ASVtable, Merged_classifications, by="ASV")

# Ranked abundance
ranked <- df %>%
  gather(2:100, key="SeqID", value="counts") %>%
  group_by(SeqID,Reference) %>%
  arrange(desc(counts)) %>%
  mutate(rank = row_number(), relative_abundance = counts/sum(counts)*100) %>%
  ungroup() %>%
  gather(2:8, key="Taxonomic_rank", value="Taxonomy") %>%
  mutate(Reference = factor(Reference, levels = c("AsCoM","GG","GTDB", "RDP", "SILVA")))

Sample_metadata <- read.delim("data/Metadata_Askov.txt",
                      sep = "\t",
                      header = TRUE,
                      quote = "\"",
                      fill = TRUE,
                      check.names = FALSE,
                      stringsAsFactors = FALSE) 

ranked_w_metadata <- left_join(ranked, Sample_metadata, by="SeqID")%>% mutate(Environment = factor(Compartment, levels = c("Soil","Rhizosphere", "Endosphere", "Nodule"))) 

ranked_w_metadata_SRE <- left_join(ranked, Sample_metadata, by="SeqID") %>%
  filter(Compartment %in% c("Soil", "Rhizosphere", "Endosphere"))
```

Summarize_data
```{r, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
#Data for Simon
RA_0.01 <- ASVtable %>%
  gather(2:100, key="SeqID", value="counts") %>%
  group_by(SeqID) %>%
  arrange(desc(counts)) %>%
  mutate(rank = row_number(), relative_abundance = counts/sum(counts)*100) %>%
  group_by(ASV) %>% 
  select(ASV, relative_abundance, SeqID) %>%
  filter(relative_abundance < 0.001)

write.csv(RA_0.01, "output/RA_0.01.csv")

#Summarize for relative abundance >0.01%
Summary_Genus <- ranked_w_metadata_SRE %>%
  filter(relative_abundance > 0.01, Taxonomic_rank==c("Genus")) %>%
  group_by(SeqID, Compartment, Reference, Taxonomic_rank) %>%
  summarize("Classified"=100-(sum(is.na(Taxonomy))/n()*100)) 

Summary_Species <- ranked_w_metadata_SRE %>%
  filter(relative_abundance > 0.01, Taxonomic_rank==c("Species")) %>%
  group_by(SeqID, Compartment, Reference, Taxonomic_rank) %>%
  summarize("Classified"=100-(sum(is.na(Taxonomy))/n()*100)) 

Summary <- bind_rows(Summary_Genus,Summary_Species)


Summary_Mean_and_stdev <- Summary %>%
  group_by(Reference, Taxonomic_rank) %>%
  summarize("Mean"=mean(Classified),
            "Stdev"=sd(Classified))

Summary_ratio <- ranked_w_metadata_SRE %>% filter(relative_abundance > 0.01, Taxonomic_rank==c("Family")) %>% group_by(SeqID, Compartment, Reference, Taxonomic_rank, Taxonomy) %>% summarize("Ratio"=((count(Taxonomy=="f:Mitochondia"))/n()*100)

```

## Plot histogram
```{r, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
Summary$Compartment_f =factor(Summary$Compartment,levels=c("Soil","Rhizosphere","Endosphere"))

Summary2$Compartment_f = factor(Summary2$Compartment, levels=c("Soil","Rhizosphere"))

a <- ifelse(Summary$Reference == "AsCoM", "darkred", "black")

p1 <- ggplot(data=Summary, aes(x=Reference, y=Classified, fill=Reference)) +
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.1, fill="white")+
  ylab("Percent of ASVs classified") +
  scale_fill_brewer(palette="RdYlBu")+
  theme(axis.title.x=element_blank()) +
  scale_y_continuous(limits = c(0, 100), breaks=seq(0,100,10)) +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 90, vjust=0.5, hjust = 1, colour = a)) + facet_grid(vars(Taxonomic_rank), vars(Compartment_f)) 

ggsave(filename="output/Figure3_Classification.pdf", plot=p1, width=7, height=4, useDingbats=FALSE, limitsize=FALSE)

```