---
title: "Figure SX: Alpha-diversity analyses"
author: "Morten K. D. Dueholm"
date: "2022-04-12"
---

#Load packages
```{r load_packages, message=FALSE, warning=FALSE, echo=FALSE, include=FALSE}
library(ampvis2)
library(patchwork)
library(FSA)
library(rcompanion)
```

#Load data
```{r MD data}
#load metadata
Sample_metadata <- read.csv("data/DataS1_AD_metadata_220401.txt", sep="\t")
Sample_metadata[Sample_metadata==""]<-NA
Sample_metadata <- mutate(Sample_metadata, Sample_id = str_extract(SampleID, pattern = "[A-Z,2]{2,3}-[0-9]{2}-[A,B]"))


#V13
V13_metadata <- read.csv("data/V13_Metadata.txt", sep=",",header = FALSE)
V13_metadata <- mutate(V13_metadata, Sample_id = str_extract(V2, pattern = "[A-Z,2]{2,3}-[0-9]{2}-[A,B]"))
V13_metadata <- merge.data.frame(V13_metadata, Sample_metadata, by ="Sample_id", all.x = TRUE) %>%
  select(V1, everything())

d13 <- amp_load(otutab = "data/V13_ASVtab.txt", 
                taxonomy = "data/V13ASV_vs_MiDAS_5.0.sintax",
                metadata = V13_metadata)

#V4
V4_metadata <- read.csv("data/V4c_Metadata.txt", sep=",",header = FALSE)
V4_metadata <- mutate(V4_metadata, Sample_id = str_extract(V2, pattern = "[A-Z,2]{2,3}-[0-9]{2}-[A,B]"))
V4_metadata <- merge.data.frame(V4_metadata, Sample_metadata, by ="Sample_id", all.x = TRUE) %>%
  select(V1, everything())

d4 <- amp_load(otutab = "data/V4_ASVtab.txt", 
                taxonomy = "data/V4ASV_vs_MiDAS_5.0.sintax",
                metadata = V4_metadata)
#V35
V35_metadata <- read.csv("data/V35_Metadata.txt", sep=",",header = FALSE)
V35_metadata <- mutate(V35_metadata, Sample_id = str_extract(V2, pattern = "[A-Z,2]{2,3}-[0-9]{2}-[A,B]"))
V35_metadata <- merge.data.frame(V35_metadata, Sample_metadata, by ="Sample_id", all.x = TRUE) %>%
  select(V1, everything())

d35 <- amp_load(otutab = "data/V35_reverse_250bp_ASVtab.txt", 
                taxonomy = "data/V35_reverse_250bp_ASV_vs_MiDAS_5.0.sintax",
                metadata = V35_metadata)
```
#alpha_diversity based on V1-V3 data
```{r V1-V3 alpha diversity}
#prepare rarefied dataset for diversity analysis
d13r <- amp_subset_samples(d13, rarefy = 10000, minreads = 10000)

#calculate alpha diversity indices
V13_alfa <-amp_alphadiv(d13r)

######################
#~Digester technology
######################
V13_alfa_tech <- V13_alfa %>%
  filter(Digester_technology %in% c("RCM/CSTR","UASB","TSAD","Plug-Flow")) %>%
  mutate(Digester_technology2 = gsub("-","",Digester_technology))

p1a1 <- 
  ggplot(data = V13_alfa_tech, aes(x = Digester_technology, y = ObservedOTUs, fill = Digester_technology))+
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.2, fill="white")+
  xlab(NULL) +
  scale_y_continuous("ASV richness", limits = c(0, 2500)) +
  theme(legend.position = "none",
        axis.text.y = element_text(colour = "black"), 
        axis.text.x = element_blank()) +
  scale_fill_brewer(palette="Set2") +
  stat_compare_means(label.y=2500)

p1a2 <- 
  ggplot(data = V13_alfa_tech, aes(x = Digester_technology, y = invSimpson, fill = Digester_technology))+
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.2, fill="white")+
  xlab("Digester technology") +
  scale_y_continuous("Inverse Simpson (1/D)", limits = c(0, 300)) +
  theme(legend.position = "none",
        axis.text.y = element_text(colour = "black"), 
        axis.text.x = element_text(colour = "black", vjust = 1, hjust = 1, angle = 45)) +
  scale_fill_brewer(palette="Set2") +
  stat_compare_means(label.y=300) 

######################
#~Primary substrate
######################
# Remove samples without metadata
V13_alfa_substrate <- V13_alfa  %>%
  filter(Primary_substrate %in% c("Wastewater sludge","Industrial","Manure","Food waste"))

p1b1 <- 
  ggplot(data = V13_alfa_substrate, aes(x = Primary_substrate, y = ObservedOTUs, fill = Primary_substrate))+
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.2, fill="white")+
  xlab(NULL) +
  scale_y_continuous(NULL, limits = c(0, 2500)) +
  theme(legend.position = "none",
        axis.text.y = element_blank(),
        axis.text.x = element_blank()) +
  scale_fill_brewer(palette="Set2") +
  stat_compare_means(label.y=2500)

p1b2 <- 
  ggplot(data = V13_alfa_substrate, aes(x = Primary_substrate, y = invSimpson, fill = Primary_substrate))+
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.2, fill="white")+
  xlab("Primary substrate") +
  scale_y_continuous(NULL, limits = c(0, 300)) +
  theme(legend.position = "none",
        axis.text.y = element_blank(), 
        axis.text.x = element_text(colour = "black", vjust = 1, hjust = 1, angle = 45)) +
  scale_fill_brewer(palette="Set2") +
  stat_compare_means(label.y=300) 

############################
#~Mesophilic vs thermophilic
############################
# Remove samples without metadata
V13_alfa_temp_range <- V13_alfa[ !is.na(V13_alfa$Temperature_range), ]

# Select groups for statistical comparison
p1c1 <- 
  ggplot(data = V13_alfa_temp_range, aes(x = Temperature_range, y = ObservedOTUs, fill = Temperature_range))+
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.2, fill="white")+
  xlab(NULL) +
  scale_y_continuous(NULL, limits = c(0, 2500)) +
  theme(legend.position = "none",
        axis.text.y = element_blank(), 
        axis.text.x = element_blank()) +
  scale_fill_brewer(palette="Set2") +
  stat_compare_means(label.y=2500)

p1c2 <- 
  ggplot(data = V13_alfa_temp_range, aes(x = Temperature_range, y = invSimpson, fill = Temperature_range))+
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.2, fill="white")+
  xlab("Temperature") +
  scale_y_continuous(NULL, limits = c(0, 300)) +
  theme(legend.position = "none",
        axis.text.y = element_blank(), 
        axis.text.x = element_text(colour = "black", vjust = 1, hjust = 1, angle = 45)) +
  scale_fill_brewer(palette="Set2") +
  stat_compare_means(label.y=300) 

######################
#~Continent
######################
V13_alfa_Continent <- V13_alfa[ !is.na(V13_alfa$Continent), ]

p1d1 <- 
  ggplot(data = V13_alfa_Continent, aes(x = Continent, y = ObservedOTUs, fill = Continent))+
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.2, fill="white")+
  xlab(NULL) +
  scale_y_continuous(NULL, limits = c(0, 2500)) +
  theme(legend.position = "none",
        axis.text.y = element_blank(), 
        axis.text.x = element_blank()) +
  scale_fill_brewer(palette="Set2") +
  stat_compare_means(label.y=2500)

p1d2 <- 
  ggplot(data = V13_alfa_Continent, aes(x = Continent, y = invSimpson, fill = Continent))+
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.2, fill="white")+
  xlab("Continent") +
  scale_y_continuous(NULL, limits = c(0, 300)) +
  theme(legend.position = "none",
        axis.text.y = element_blank(), 
        axis.text.x = element_text(colour = "black", vjust = 1, hjust = 1, angle = 45)) +
  scale_fill_brewer(palette="Set2") +
  
  stat_compare_means(label.y=300) 


######################
#~Statistical analysis
######################
V13_Dunn_Obs_tech <- dunnTest(ObservedOTUs ~ Digester_technology2, data=V13_alfa_tech, method="bonferroni")$res %>%
  cldList(P.adj ~ Comparison, data=., threshold = 0.01)

V13_Dunn_invS_tech <- dunnTest(invSimpson ~ Digester_technology2, data=V13_alfa_tech, method="bonferroni")$res %>%
  cldList(P.adj ~ Comparison, data=., threshold = 0.01)

V13_Dunn_Obs_substrate <- dunnTest(ObservedOTUs ~ Primary_substrate, data=V13_alfa_substrate, method="bonferroni")$res %>%
  cldList(P.adj ~ Comparison, data=., threshold = 0.01)

V13_Dunn_invS_substrate <- dunnTest(invSimpson ~ Primary_substrate, data=V13_alfa_substrate, method="bonferroni")$res %>%
  cldList(P.adj ~ Comparison, data=., threshold = 0.01)

V13_Dunn_Obs_temp <- dunnTest(ObservedOTUs ~ Temperature_range, data=V13_alfa_temp_range, method="bonferroni")$res %>%
  cldList(P.adj ~ Comparison, data=., threshold = 0.01)

V13_Dunn_invS_temp <- dunnTest(invSimpson ~ Temperature_range, data=V13_alfa_temp_range, method="bonferroni")$res %>%
  cldList(P.adj ~ Comparison, data=., threshold = 0.01)

V13_Dunn_Obs_Cont <- dunnTest(ObservedOTUs ~ Continent, data=V13_alfa_Continent, method="bonferroni")$res %>%
  cldList(P.adj ~ Comparison, data=., threshold = 0.01)

V13_Dunn_invS_Cont <- dunnTest(invSimpson ~ Continent, data=V13_alfa_Continent, method="bonferroni")$res %>%
  cldList(P.adj ~ Comparison, data=., threshold = 0.01)
```
#alpha_diversity based on V4 data
```{r V4 alpha diversity}
#prepare rarefied dataset for diversity analysis
d4r <- amp_subset_samples(d4, rarefy = 10000, minreads = 10000)

#calculate alpha diversity indices
V4_alfa <-amp_alphadiv(d4r)

######################
#~Digester technology
######################
V4_alfa_tech <- V4_alfa %>%
  filter(Digester_technology %in% c("RCM/CSTR","UASB","TSAD","Plug-Flow")) %>%
  mutate(Digester_technology2 = gsub("-","",Digester_technology))

p2a1 <- 
  ggplot(data = V4_alfa_tech, aes(x = Digester_technology, y = ObservedOTUs, fill = Digester_technology))+
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.2, fill="white")+
  xlab(NULL) +
  scale_y_continuous("ASV richness", limits = c(0, 2500)) +
  theme(legend.position = "none",
        axis.text.y = element_text(colour = "black"), 
        axis.text.x = element_blank()) +
  scale_fill_brewer(palette="Set2", drop=FALSE) +
  scale_x_discrete(drop=FALSE) +
  stat_compare_means(label.y=2500)

p2a2 <- 
  ggplot(data = V4_alfa_tech, aes(x = Digester_technology, y = invSimpson, fill = Digester_technology))+
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.2, fill="white")+
  xlab("Digester technology") +
  scale_y_continuous("Inverse Simpson (1/D)", limits = c(0, 250)) +
  theme(legend.position = "none",
        axis.text.y = element_text(colour = "black"), 
        axis.text.x = element_text(colour = "black", vjust = 1, hjust = 1, angle = 45)) +
  scale_fill_brewer(palette="Set2", drop=FALSE) +
  scale_x_discrete(drop=FALSE) +
  stat_compare_means(label.y=250) 

######################
#~Primary substrate
######################
# Remove samples without metadata
V4_alfa_substrate <- V4_alfa  %>%
  filter(Primary_substrate %in% c("Wastewater sludge","Industrial","Manure","Food waste"))

p2b1 <- 
  ggplot(data = V4_alfa_substrate, aes(x = Primary_substrate, y = ObservedOTUs, fill = Primary_substrate))+
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.2, fill="white")+
  xlab(NULL) +
  scale_y_continuous(NULL, limits = c(0, 2500)) +
  theme(legend.position = "none",
        axis.text.y = element_blank(),
        axis.text.x = element_blank()) +
  scale_fill_brewer(palette="Set2") +
  stat_compare_means(label.y=2500)

p2b2 <- 
  ggplot(data = V4_alfa_substrate, aes(x = Primary_substrate, y = invSimpson, fill = Primary_substrate))+
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.2, fill="white")+
  xlab("Primary substrate") +
  scale_y_continuous(NULL, limits = c(0, 250)) +
  theme(legend.position = "none",
        axis.text.y = element_blank(), 
        axis.text.x = element_text(colour = "black", vjust = 1, hjust = 1, angle = 45)) +
  scale_fill_brewer(palette="Set2") +
  stat_compare_means(label.y=250) 

############################
#~Mesophilic vs thermophilic
############################
# Remove samples without metadata
V4_alfa_temp_range <- V4_alfa[ !is.na(V4_alfa$Temperature_range), ]

# Select groups for statistical comparison
p2c1 <- 
  ggplot(data = V4_alfa_temp_range, aes(x = Temperature_range, y = ObservedOTUs, fill = Temperature_range))+
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.2, fill="white")+
  xlab(NULL) +
  scale_y_continuous(NULL, limits = c(0, 2500)) +
  theme(legend.position = "none",
        axis.text.y = element_blank(), 
        axis.text.x = element_blank()) +
  scale_fill_brewer(palette="Set2",drop=FALSE) +
  scale_x_discrete(drop=FALSE) +
  stat_compare_means(label.y=2500)

p2c2 <- 
  ggplot(data = V4_alfa_temp_range, aes(x = Temperature_range, y = invSimpson, fill = Temperature_range))+
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.2, fill="white")+
  xlab("Temperature") +
  scale_y_continuous(NULL, limits = c(0, 250)) +
  theme(legend.position = "none",
        axis.text.y = element_blank(), 
        axis.text.x = element_text(colour = "black", vjust = 1, hjust = 1, angle = 45)) +
  scale_fill_brewer(palette="Set2",drop=FALSE) +
  scale_x_discrete(drop=FALSE) +
  stat_compare_means(label.y=250) 

######################
#~Continent
######################
V4_alfa_Continent <- V4_alfa[ !is.na(V4_alfa$Continent), ]

p2d1 <- 
  ggplot(data = V4_alfa_Continent, aes(x = Continent, y = ObservedOTUs, fill = Continent))+
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.2, fill="white")+
  xlab(NULL) +
  scale_y_continuous(NULL, limits = c(0, 2500)) +
  theme(legend.position = "none",
        axis.text.y = element_blank(), 
        axis.text.x = element_blank()) +
  scale_fill_brewer(palette="Set2", drop=FALSE) +
  scale_x_discrete(drop=FALSE) +
  stat_compare_means(label.y=2500)

p2d2 <- 
  ggplot(data = V4_alfa_Continent, aes(x = Continent, y = invSimpson, fill = Continent))+
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.2, fill="white")+
  xlab("Continent") +
  scale_y_continuous(NULL, limits = c(0, 250)) +
  theme(legend.position = "none",
        axis.text.y = element_blank(), 
        axis.text.x = element_text(colour = "black", vjust = 1, hjust = 1, angle = 45)) +
  scale_fill_brewer(palette="Set2", drop=FALSE) +
  scale_x_discrete(drop=FALSE) +
  stat_compare_means(label.y=250) 


######################
#~Statistical analysis
######################
V4_Dunn_Obs_tech <- dunnTest(ObservedOTUs ~ Digester_technology2, data=V4_alfa_tech, method="bonferroni")$res %>%
  cldList(P.adj ~ Comparison, data=., threshold = 0.01)

V4_Dunn_invS_tech <- dunnTest(invSimpson ~ Digester_technology2, data=V4_alfa_tech, method="bonferroni")$res %>%
  cldList(P.adj ~ Comparison, data=., threshold = 0.01)

V4_Dunn_Obs_substrate <- dunnTest(ObservedOTUs ~ Primary_substrate, data=V4_alfa_substrate, method="bonferroni")$res %>%
  cldList(P.adj ~ Comparison, data=., threshold = 0.01)

V4_Dunn_invS_substrate <- dunnTest(invSimpson ~ Primary_substrate, data=V4_alfa_substrate, method="bonferroni")$res %>%
  cldList(P.adj ~ Comparison, data=., threshold = 0.01)

V4_Dunn_Obs_temp <- dunnTest(ObservedOTUs ~ Temperature_range, data=V4_alfa_temp_range, method="bonferroni")$res %>%
  cldList(P.adj ~ Comparison, data=., threshold = 0.01)

V4_Dunn_invS_temp <- dunnTest(invSimpson ~ Temperature_range, data=V4_alfa_temp_range, method="bonferroni")$res %>%
  cldList(P.adj ~ Comparison, data=., threshold = 0.01)

V4_Dunn_Obs_Cont <- dunnTest(ObservedOTUs ~ Continent, data=V4_alfa_Continent, method="bonferroni")$res %>%
  cldList(P.adj ~ Comparison, data=., threshold = 0.01)

V4_Dunn_invS_Cont <- dunnTest(invSimpson ~ Continent, data=V4_alfa_Continent, method="bonferroni")$res %>%
  cldList(P.adj ~ Comparison, data=., threshold = 0.01)
```
#alpha_diversity based on V35 data
```{r V35 alpha diversity}
#prepare rarefied dataset for diversity analysis
d35_arc <- amp_subset_taxa(d35, tax_vector = "k__Archaea", normalise = FALSE)
d35r <- amp_subset_samples(d35_arc, rarefy = 10000, minreads = 10000)

#calculate alpha diversity indices
V35_alfa <-amp_alphadiv(d35r)

######################
#~Digester technology
######################
V35_alfa_tech <- V35_alfa %>%
  filter(Digester_technology %in% c("RCM/CSTR","UASB","TSAD","Plug-Flow")) %>%
  mutate(Digester_technology2 = gsub("-","",Digester_technology))

p3a1 <- 
  ggplot(data = V35_alfa_tech, aes(x = Digester_technology, y = ObservedOTUs, fill = Digester_technology))+
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.2, fill="white")+
  xlab(NULL) +
  scale_y_continuous("ASV richness", limits = c(0, 200)) +
  theme(legend.position = "none",
        axis.text.y = element_text(colour = "black"), 
        axis.text.x = element_blank()) +
  scale_fill_brewer(palette="Set2",drop=FALSE) +
  scale_x_discrete(drop=FALSE) +
  stat_compare_means(label.y=200)

p3a2 <- 
  ggplot(data = V35_alfa_tech, aes(x = Digester_technology, y = invSimpson, fill = Digester_technology))+
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.2, fill="white")+
  xlab("Digester technology") +
  scale_y_continuous("Inverse Simpson (1/D)", limits = c(0, 10)) +
  theme(legend.position = "none",
        axis.text.y = element_text(colour = "black"), 
        axis.text.x = element_text(colour = "black", vjust = 1, hjust = 1, angle = 45)) +
  scale_fill_brewer(palette="Set2",drop=FALSE) +
  scale_x_discrete(drop=FALSE) +
  stat_compare_means(label.y=10) 

######################
#~Primary substrate
######################
# Remove samples without metadata
V35_alfa_substrate <- V35_alfa  %>%
  filter(Primary_substrate %in% c("Wastewater sludge","Industrial","Manure","Food waste"))

p3b1 <- 
  ggplot(data = V35_alfa_substrate, aes(x = Primary_substrate, y = ObservedOTUs, fill = Primary_substrate))+
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.2, fill="white")+
  xlab(NULL) +
  scale_y_continuous(NULL, limits = c(0, 200)) +
  theme(legend.position = "none",
        axis.text.y = element_blank(),
        axis.text.x = element_blank()) +
  scale_fill_brewer(palette="Set2",drop=FALSE) +
   scale_x_discrete(drop=FALSE) +
  stat_compare_means(label.y=200)

p3b2 <- 
  ggplot(data = V35_alfa_substrate, aes(x = Primary_substrate, y = invSimpson, fill = Primary_substrate))+
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.2, fill="white")+
  xlab("Primary substrate") +
  scale_y_continuous(NULL, limits = c(0, 10)) +
  theme(legend.position = "none",
        axis.text.y = element_blank(), 
        axis.text.x = element_text(colour = "black", vjust = 1, hjust = 1, angle = 45)) +
  scale_fill_brewer(palette="Set2",drop=FALSE) +
  scale_x_discrete(drop=FALSE) +
  stat_compare_means(label.y=10) 

############################
#~Mesophilic vs thermophilic
############################
# Remove samples without metadata
V35_alfa_temp_range <- V35_alfa[ !is.na(V35_alfa$Temperature_range), ]

# Select groups for statistical comparison
p3c1 <- 
  ggplot(data = V35_alfa_temp_range, aes(x = Temperature_range, y = ObservedOTUs, fill = Temperature_range))+
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.2, fill="white")+
  xlab(NULL) +
  scale_y_continuous(NULL, limits = c(0, 200)) +
  theme(legend.position = "none",
        axis.text.y = element_blank(), 
        axis.text.x = element_blank()) +
  scale_fill_brewer(palette="Set2",drop=FALSE) +
  scale_x_discrete(drop=FALSE) +
  stat_compare_means(label.y=200)

p3c2 <- 
  ggplot(data = V35_alfa_temp_range, aes(x = Temperature_range, y = invSimpson, fill = Temperature_range))+
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.2, fill="white")+
  xlab("Temperature") +
  scale_y_continuous(NULL, limits = c(0, 10)) +
  theme(legend.position = "none",
        axis.text.y = element_blank(), 
        axis.text.x = element_text(colour = "black", vjust = 1, hjust = 1, angle = 45)) +
  scale_fill_brewer(palette="Set2",drop=FALSE) +
  scale_x_discrete(drop=FALSE) +
  stat_compare_means(label.y=10) 

######################
#~Continent
######################
V35_alfa_Continent <- V35_alfa[ !is.na(V35_alfa$Continent), ]

p3d1 <- 
  ggplot(data = V35_alfa_Continent, aes(x = Continent, y = ObservedOTUs, fill = Continent))+
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.2, fill="white")+
  xlab(NULL) +
  scale_y_continuous(NULL, limits = c(0, 200)) +
  theme(legend.position = "none",
        axis.text.y = element_blank(), 
        axis.text.x = element_blank()) +
  scale_fill_brewer(palette="Set2",drop=FALSE) +
  scale_x_discrete(drop=FALSE) +
  stat_compare_means(label.y=200)

p3d2 <- 
  ggplot(data = V35_alfa_Continent, aes(x = Continent, y = invSimpson, fill = Continent))+
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.2, fill="white")+
  xlab("Continent") +
  scale_y_continuous(NULL, limits = c(0, 10)) +
  theme(legend.position = "none",
        axis.text.y = element_blank(), 
        axis.text.x = element_text(colour = "black", vjust = 1, hjust = 1, angle = 45)) +
  scale_fill_brewer(palette="Set2",drop=FALSE) +
  scale_x_discrete(drop=FALSE) +
  stat_compare_means(label.y=10) 


######################
#~Statistical analysis
######################
V35_Dunn_Obs_tech <- dunnTest(ObservedOTUs ~ Digester_technology2, data=V35_alfa_tech, method="bonferroni")$res %>%
  cldList(P.adj ~ Comparison, data=., threshold = 0.01)

V35_Dunn_invS_tech <- dunnTest(invSimpson ~ Digester_technology2, data=V35_alfa_tech, method="bonferroni")$res %>%
  cldList(P.adj ~ Comparison, data=., threshold = 0.01)

V35_Dunn_Obs_substrate <- dunnTest(ObservedOTUs ~ Primary_substrate, data=V35_alfa_substrate, method="bonferroni")$res %>%
  cldList(P.adj ~ Comparison, data=., threshold = 0.01)

V35_Dunn_invS_substrate <- dunnTest(invSimpson ~ Primary_substrate, data=V35_alfa_substrate, method="bonferroni")$res %>%
  cldList(P.adj ~ Comparison, data=., threshold = 0.01)

V35_Dunn_Obs_temp <- dunnTest(ObservedOTUs ~ Temperature_range, data=V35_alfa_temp_range, method="bonferroni")$res %>%
  cldList(P.adj ~ Comparison, data=., threshold = 0.01)

V35_Dunn_invS_temp <- dunnTest(invSimpson ~ Temperature_range, data=V35_alfa_temp_range, method="bonferroni")$res %>%
  cldList(P.adj ~ Comparison, data=., threshold = 0.01)

V35_Dunn_Obs_Cont <- dunnTest(ObservedOTUs ~ Continent, data=V35_alfa_Continent, method="bonferroni")$res %>%
  cldList(P.adj ~ Comparison, data=., threshold = 0.01)

V35_Dunn_invS_Cont <- dunnTest(invSimpson ~ Continent, data=V35_alfa_Continent, method="bonferroni")$res %>%
  cldList(P.adj ~ Comparison, data=., threshold = 0.01)
```

#Export combined figure
```{r V35 alpha diversity}

######################
#~Combined figure
######################

p <- ( p1a1 | p1b1 | p1c1 | p1d1) / ( p1a2 | p1b2 | p1c2 | p1d2) /
     ( p2a1 | p2b1 | p2c1 | p2d1) / ( p2a2 | p2b2 | p2c2 | p2d2) /
     ( p3a1 | p3b1 | p3c1 | p3d1) / ( p3a2 | p3b2 | p3c2 | p3d2)

ggsave(filename="output/FigureS4_Alpha_diversity.pdf", plot=p, width=10, height=12, useDingbats=FALSE, limitsize=FALSE)
```