---
title: "Figure 2: MiDAS5 database evaluation"
author: "Morten K. D. Dueholm"
date: "2022-04-05"
---

## R-packages
```{r, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
library(data.table)
library(tidyverse)
library(patchwork)
```

## Create coverage graphs V1-V3
```{r, echo=FALSE, message=FALSE, warning=FALSE}
### Function to load read mapping data
read_amp_mappings <- function(input) {
  map <- data.table::fread(input,
                      sep = "\t",
                      header = FALSE,
                      quote = "\"",
                      fill = TRUE,
                      check.names = FALSE,
                      stringsAsFactors = FALSE,
                      select = c(1,3))
  map <- setnames(map, "V1", "ASV")
  map <- setnames(map, "V3", gsub(".*vs_(.+).b6", "\\1", paste(input)))
  map <- map[order(, readr::parse_number(ASV))]}

### Read mapping results for V1-V3
a <- read_amp_mappings("data/V13ASV_vs_MiDAS_5.0.b6")

# Read ASV table
ASVtable <- data.table::fread("data/V13_ASVtab.txt",
                      sep = "\t",
                      header = TRUE,
                      quote = "\"",
                      fill = TRUE,
                      check.names = FALSE,
                      stringsAsFactors = FALSE)
ASVtable <- setnames(ASVtable, 1, "ASV")
ASVtable <- ASVtable[order(, readr::parse_number(ASV))]

# Read metadata
#load metadata
Sample_metadata <- read.csv("data/DataS1_AD_metadata_220401.txt", sep="\t")
Sample_metadata$Primary_substrate[is.na(Sample_metadata$Primary_substrate)] <- "Other"
Sample_metadata$Temperature_range[is.na(Sample_metadata$Temperature_range)] <- "Other"
Sample_metadata[Sample_metadata==""]<-NA
Sample_metadata <- mutate(Sample_metadata, Sample_id = str_extract(SampleID, pattern = "[A-Z,2]{2,3}-[0-9]{2}-[A,B]"))
Sample_metadata <- mutate(Sample_metadata, AD_id = str_extract(SampleID, pattern = "[A-Z,2]{2,3}-[0-9]{2}"))

#V13
V13_metadata <- read.csv("data/V13_Metadata.txt", sep=",",header = FALSE)
V13_metadata <- mutate(V13_metadata, Sample_id = str_extract(V2, pattern = "[A-Z,2]{2,3}-[0-9]{2}-[A,B]"))
V13_metadata <- merge.data.frame(V13_metadata, Sample_metadata, by ="Sample_id", all.x = TRUE) %>%
  select(V1, everything()) %>%
  rename(SeqID="V1")

# Merge ASV table and mappings
df <- merge.data.table(ASVtable, a, by="ASV")

# Rearrange data.table into long format with Database and SeqID as variables
df_long <- melt.data.table(df, id.vars = 1:ncol(ASVtable), measure.vars = (ncol(ASVtable)+1):(ncol(ASVtable)+ncol(a)-1), variable.name = "Database", value.name = "Identity") 
df_long <- melt.data.table(df_long, id.vars = c("ASV","Database","Identity"), measure.vars = 2:ncol(ASVtable), variable.name = "SeqID", value.name = "Counts") 
df_long <- df_long[, Rel_abun := Counts/sum(Counts)*100, by=.(SeqID,Database)]

#Merge data.table with metadata
df_long <- merge.data.table(df_long, V13_metadata, by="SeqID")
df_long2 <- df_long[Primary_substrate %in% c("Food waste","Industrial","Manure","Wastewater sludge")][Temperature_range %in% c("Mesophilic","Thermophilic")]

### Effect of primary substrate
# Calculate with coverage of ASVs after subsetting based on relative abundance (>= 0.01).
coverage_v13 <-df_long2[Rel_abun >= 0.01, .("coverage"=sum(Rel_abun)), by=.(SeqID,Primary_substrate,Temperature_range)][,.(mean=mean(coverage),sd=sd(coverage),n=.N), by=.(Primary_substrate,Temperature_range)]

#Calculate fraction of ASVs with 99% matches in the reference databases
r_v13 <- df_long2[Rel_abun>0.01 & Counts>0, .("Hits"=sum(Identity>=99)/.N*100,
            "detected_amplicons"=.N,"Primer"="V1-V3"),
            by=.(SeqID,Primary_substrate,Temperature_range)]

#Calculate fraction of ASVs with 99% matches in the reference databases
Summary_v13 <- r_v13[, .("Mean"=mean(Hits),
                  "Sd"=sd(Hits)), 
              by=.(Primary_substrate,Temperature_range)]

## Plot histogram
p1 <- ggplot(data=r_v13, aes(x=Primary_substrate, y=Hits, fill=Primary_substrate)) +
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.1, fill="white")+
  ylab("Percent of ASVs with high-identity references (>99% ID)") +
  scale_fill_brewer(palette="Set2")+
  theme(axis.title.x=element_blank()) +
  scale_y_continuous(limits = c(0, 100), breaks=seq(0,100,10)) +
  theme(legend.position = "none") +
  facet_grid(~Temperature_range) +
  theme(axis.text.x = element_text(angle = 90, vjust=0.5, hjust = 1))

ggsave(filename="output/FigureX_Database_evaluation_types_v13.pdf", plot=p1, width=6, height=4, useDingbats=FALSE, limitsize=FALSE)
```

## Create coverage graphs V4
```{r, echo=FALSE, message=FALSE, warning=FALSE}
### Function to load read mapping data
read_amp_mappings <- function(input) {
  map <- data.table::fread(input,
                      sep = "\t",
                      header = FALSE,
                      quote = "\"",
                      fill = TRUE,
                      check.names = FALSE,
                      stringsAsFactors = FALSE,
                      select = c(1,3))
  map <- setnames(map, "V1", "ASV")
  map <- setnames(map, "V3", gsub(".*vs_(.+).b6", "\\1", paste(input)))
  map <- map[order(, readr::parse_number(ASV))]}

### Read mapping results for V4
a <- read_amp_mappings("data/V4ASV_vs_MiDAS_5.0.b6")

# Read ASV table
ASVtable <- data.table::fread("data/V4_ASVtab.txt",
                      sep = "\t",
                      header = TRUE,
                      quote = "\"",
                      fill = TRUE,
                      check.names = FALSE,
                      stringsAsFactors = FALSE)
ASVtable <- setnames(ASVtable, 1, "ASV")
ASVtable <- ASVtable[order(, readr::parse_number(ASV))]

# Read metadata
#load metadata
Sample_metadata <- read.csv("data/DataS1_AD_metadata_220401.txt", sep="\t")
Sample_metadata$Primary_substrate[is.na(Sample_metadata$Primary_substrate)] <- "Other"
Sample_metadata$Temperature_range[is.na(Sample_metadata$Temperature_range)] <- "Other"
Sample_metadata[Sample_metadata==""]<-NA
Sample_metadata <- mutate(Sample_metadata, Sample_id = str_extract(SampleID, pattern = "[A-Z,2]{2,3}-[0-9]{2}-[A,B]"))
Sample_metadata <- mutate(Sample_metadata, AD_id = str_extract(SampleID, pattern = "[A-Z,2]{2,3}-[0-9]{2}"))

#V4
V4_metadata <- read.csv("data/V4c_Metadata.txt", sep=",",header = FALSE)
V4_metadata <- mutate(V4_metadata, Sample_id = str_extract(V2, pattern = "[A-Z,2]{2,3}-[0-9]{2}-[A,B]"))
V4_metadata <- merge.data.frame(V4_metadata, Sample_metadata, by ="Sample_id", all.x = TRUE) %>%
  select(V1, everything()) %>%
  rename(SeqID="V1")

# Merge ASV table and mappings
df <- merge.data.table(ASVtable, a, by="ASV")

# Rearrange data.table into long format with Database and SeqID as variables
df_long <- melt.data.table(df, id.vars = 1:ncol(ASVtable), measure.vars = (ncol(ASVtable)+1):(ncol(ASVtable)+ncol(a)-1), variable.name = "Database", value.name = "Identity") 
df_long <- melt.data.table(df_long, id.vars = c("ASV","Database","Identity"), measure.vars = 2:ncol(ASVtable), variable.name = "SeqID", value.name = "Counts") 
df_long <- df_long[, Rel_abun := Counts/sum(Counts)*100, by=.(SeqID,Database)]

#Merge data.table with metadata
df_long <- merge.data.table(df_long, V4_metadata, by="SeqID")
df_long2 <- df_long[Primary_substrate %in% c("Food waste","Industrial","Manure","Wastewater sludge")][Temperature_range %in% c("Mesophilic","Thermophilic")]

### Effect of primary substrate
# Calculate with coverage of ASVs after subsetting based on relative abundance (>= 0.01).
coverage_v4 <-df_long2[Rel_abun >= 0.01, .("coverage"=sum(Rel_abun)), by=.(SeqID,Primary_substrate,Temperature_range)][,.(mean=mean(coverage),sd=sd(coverage),n=.N), by=.(Primary_substrate,Temperature_range)]

#Calculate fraction of ASVs with 99% matches in the reference databases
r_v4 <- df_long2[Rel_abun>0.01 & Counts>0, .("Hits"=sum(Identity>=99)/.N*100,
            "detected_amplicons"=.N,"Primer"="V4"),
            by=.(SeqID,Primary_substrate,Temperature_range)]

#Calculate fraction of ASVs with 99% matches in the reference databases
Summary_v4 <- r_v4[, .("Mean"=mean(Hits),
                  "Sd"=sd(Hits)), 
              by=.(Primary_substrate,Temperature_range)]

## Plot histogram
p2 <- ggplot(data=r_v4, aes(x=Primary_substrate, y=Hits, fill=Primary_substrate)) +
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.1, fill="white")+
  ylab("Percent of ASVs with high-identity references (>99% ID)") +
  scale_fill_brewer(palette="Set2")+
  theme(axis.title.x=element_blank()) +
  scale_y_continuous(limits = c(0, 100), breaks=seq(0,100,10)) +
  theme(legend.position = "none") +
  facet_grid(~Temperature_range) +
  theme(axis.text.x = element_text(angle = 90, vjust=0.5, hjust = 1))

ggsave(filename="output/FigureX_Database_evaluation_types_v4.pdf", plot=p2, width=6, height=4, useDingbats=FALSE, limitsize=FALSE)
```

## Create coverage graphs V3-V5
```{r, echo=FALSE, message=FALSE, warning=FALSE}
### Function to load read mapping data
read_amp_mappings <- function(input) {
  map <- data.table::fread(input,
                      sep = "\t",
                      header = FALSE,
                      quote = "\"",
                      fill = TRUE,
                      check.names = FALSE,
                      stringsAsFactors = FALSE,
                      select = c(1,3))
  map <- setnames(map, "V1", "ASV")
  map <- setnames(map, "V3", gsub(".*vs_(.+).b6", "\\1", paste(input)))
  map <- map[order(, readr::parse_number(ASV))]}

### Read mapping results for V3-V5
a <- read_amp_mappings("data/V35_reverse_250bp_ASV_vs_MiDAS_5.0.b6")

# Read ASV table
ASVtable <- data.table::fread("data/V35_reverse_250bp_ASVtab.txt",
                      sep = "\t",
                      header = TRUE,
                      quote = "\"",
                      fill = TRUE,
                      check.names = FALSE,
                      stringsAsFactors = FALSE)
ASVtable <- setnames(ASVtable, 1, "ASV")
ASVtable <- ASVtable[order(, readr::parse_number(ASV))]

# Read metadata
#load metadata
Sample_metadata <- read.csv("data/DataS1_AD_metadata_220401.txt", sep="\t")
Sample_metadata$Primary_substrate[is.na(Sample_metadata$Primary_substrate)] <- "Other"
Sample_metadata$Temperature_range[is.na(Sample_metadata$Temperature_range)] <- "Other"
Sample_metadata[Sample_metadata==""]<-NA
Sample_metadata <- mutate(Sample_metadata, Sample_id = str_extract(SampleID, pattern = "[A-Z,2]{2,3}-[0-9]{2}-[A,B]"))
Sample_metadata <- mutate(Sample_metadata, AD_id = str_extract(SampleID, pattern = "[A-Z,2]{2,3}-[0-9]{2}"))

#V3-V5
V35_metadata <- read.csv("data/V35_Metadata.txt", sep=",",header = FALSE)
V35_metadata <- mutate(V35_metadata, Sample_id = str_extract(V2, pattern = "[A-Z,2]{2,3}-[0-9]{2}-[A,B]"))
V35_metadata <- merge.data.frame(V35_metadata, Sample_metadata, by ="Sample_id", all.x = TRUE) %>%
  select(V1, everything()) %>%
  rename(SeqID="V1")

# Merge ASV table and mappings
df <- merge.data.table(ASVtable, a, by="ASV")

# Rearrange data.table into long format with Database and SeqID as variables
df_long <- melt.data.table(df, id.vars = 1:ncol(ASVtable), measure.vars = (ncol(ASVtable)+1):(ncol(ASVtable)+ncol(a)-1), variable.name = "Database", value.name = "Identity") 
df_long <- melt.data.table(df_long, id.vars = c("ASV","Database","Identity"), measure.vars = 2:ncol(ASVtable), variable.name = "SeqID", value.name = "Counts") 
df_long <- df_long[, Rel_abun := Counts/sum(Counts)*100, by=.(SeqID,Database)]

#Merge data.table with metadata
df_long <- merge.data.table(df_long, V35_metadata, by="SeqID")
df_long2 <- df_long[Primary_substrate %in% c("Food waste","Industrial","Manure","Wastewater sludge")][Temperature_range %in% c("Mesophilic","Thermophilic")]

### Effect of primary substrate
# Calculate with coverage of ASVs after subsetting based on relative abundance (>= 0.01).
coverage_V35 <-df_long2[Rel_abun >= 0.01, .("coverage"=sum(Rel_abun)), by=.(SeqID,Primary_substrate,Temperature_range)][,.(mean=mean(coverage),sd=sd(coverage),n=.N), by=.(Primary_substrate,Temperature_range)]

#Calculate fraction of ASVs with 99% matches in the reference databases
r_V35 <- df_long2[Rel_abun>0.01 & Counts>0, .("Hits"=sum(Identity>=99)/.N*100,
            "detected_amplicons"=.N,"Primer"="V3-V5"),
            by=.(SeqID,Primary_substrate,Temperature_range)]

#Calculate fraction of ASVs with 99% matches in the reference databases
Summary_V35 <- r_V35[, .("Mean"=mean(Hits),
                  "Sd"=sd(Hits)), 
              by=.(Primary_substrate,Temperature_range)]

## Plot histogram
p3 <- ggplot(data=r_V35, aes(x=Primary_substrate, y=Hits, fill=Primary_substrate)) +
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.1, fill="white")+
  ylab("Percent of ASVs with high-identity references (>99% ID)") +
  scale_fill_brewer(palette="Set2")+
  theme(axis.title.x=element_blank()) +
  scale_y_continuous(limits = c(0, 100), breaks=seq(0,100,10)) +
  theme(legend.position = "none") +
  facet_grid(~Temperature_range) +
  theme(axis.text.x = element_text(angle = 90, vjust=0.5, hjust = 1))

ggsave(filename="output/FigureX_Database_evaluation_types_V35.pdf", plot=p3, width=6, height=4, useDingbats=FALSE, limitsize=FALSE)
```

## Create combined coverage graphs
```{r, echo=FALSE, message=FALSE, warning=FALSE}
r <- rbind(r_v13, r_v4, r_V35)

p4 <- ggplot(data=r, aes(x=Primary_substrate, y=Hits, fill=Primary_substrate)) +
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.1, fill="white")+
  ylab("Percent of ASVs with high-identity references (>99% ID)") +
  scale_fill_brewer(palette="Set2")+
  theme(axis.title.x=element_blank()) +
  scale_y_continuous(limits = c(0, 100), breaks=seq(0,100,10)) +
  theme(legend.position = "none") +
  facet_grid(Temperature_range~Primer) +
  theme(axis.text.x = element_text(angle = 90, vjust=0.5, hjust = 1))

ggsave(filename="output/FigureX_Database_evaluation_types.pdf", plot=p4, width=9, height=6, useDingbats=FALSE, limitsize=FALSE)
```
